<?php
return [
    'Ohlc'              => ['allow_multiple' => true],
    'Vol'               => ['allow_multiple' => true],
    'Constant'          => ['allow_multiple' => true],
    'Operator'          => ['allow_multiple' => true],
    'Pass'              => ['allow_multiple' => true],
    'Roc'               => ['allow_multiple' => true],
    'Balance'           => ['allow_multiple' => false],
    'Ma'                => ['allow_multiple' => true],
    'Ema'               => ['allow_multiple' => true],
    'FannPrediction'    => ['allow_multiple' => false],
    'FannSignals'       => ['allow_multiple' => false],
    'Profitability'     => ['allow_multiple' => false],
    'Avg'               => ['allow_multiple' => true],
    'Rsi'               => ['allow_multiple' => true],
    'Stoch'             => ['allow_multiple' => true],
    'StochRsi'          => ['allow_multiple' => true],
    'Macd'              => ['allow_multiple' => true],
    'Bbands'            => ['allow_multiple' => true],
    'Obv'               => ['allow_multiple' => true],
    'Sar'               => ['allow_multiple' => true],
    'Ibs'               => ['allow_multiple' => true],
    'Ht'                => ['allow_multiple' => true],
    'Ad'                => ['allow_multiple' => true],
    'Adosc'             => ['allow_multiple' => true],
    'Aroon'             => ['allow_multiple' => true],
    'Aroonosc'          => ['allow_multiple' => true],
    'Bop'               => ['allow_multiple' => true],
    'Cci'               => ['allow_multiple' => true],
    'Cmo'               => ['allow_multiple' => true],
    'Dmi'               => ['allow_multiple' => true],
    'Tsf'               => ['allow_multiple' => true],
];
