<?php

return [
    'indicator' =>  [
        'input_open' => 'open',
        'input_high' => 'high',
        'input_low' => 'low',
        'input_close' => 'close',
        'show_line' => true,
        'show_annotation' => false,
        'use_functions' => [], // items are added in the constructor
    ],
    'adjustable' => [
        'input_open' => [
            'name' => 'Open Source',
            'type' => 'source',
        ],
        'input_high' => [
            'name' => 'High Source',
            'type' => 'source',
        ],
        'input_low' => [
            'name' => 'Low Source',
            'type' => 'source',
        ],
        'input_close' => [
            'name' => 'Close Source',
            'type' => 'source',
        ],
        'show_line' => [
            'name' => 'Display Sum Line',
            'type' => 'bool',
        ],
        'show_annotation' => [
            'name' => 'Display Annotation',
            'type' => 'bool',
        ],
        'use_functions' => [
            'name' => 'Search for',
            'type' => 'list',
            'items' => [], // items are added in the constructor
        ]
    ],
    'display' => [
        'name' => 'Patterns',
        'description' => 'Candlestick pattern recognition from TA-Lib',
        'mode' => 'line',
        'y-axis' => 'right',
        'top_level' => false,
    ],
    'normalize' => [
        'mode' => 'range',
        'range' => [
            'min' => -10,
            'max' => 10,
        ],
    ],
    'trader_func_prefix' => 'trader_cdl',
    'map' => [
        '2crows' => '2 Crows',
        '3blackcrows' => '3 Black Crows',
        '3inside' => '3 Inside',
        '3linestrike' => '3 Line Strike',
        '3outside' => '3 Outside',
        '3starsinsouth' => '3 Stars In South',
        '3whitesoldiers' => '3 White Soldiers',
        'abandonedbaby' => 'Abandoned Baby',
        'advanceblock' => 'Advance Block',
        'belthold' => 'Belthold',
        'breakaway' => 'Breakaway',
        'closingmarubozu' => 'Closing Marubozu',
        'concealbabyswall' => 'Conceal Baby\'s Wall',
        'counterattack' => 'Counterattack',
        'darkcloudcover' => 'Dark Cloudcover',
        'doji' => 'Doji',
        'dojistar' => 'Doji Star',
        'dragonflydoji' => 'Dragonfly Doji',
        'engulfing' => 'Engulfing',
        'eveningdojistar' => 'Evening Doji Star',
        'eveningstar' => 'Evening Star',
        'gapsidesidewhite' => 'Gapside Side White',
        'gravestonedoji' => 'Gravestone Doji',
        'hammer' => 'Hammer',
        'hangingman' => 'Hanging Man',
        'harami' => 'Harami',
        'haramicross' => 'Harami Cross',
        'highwave' => 'Highwave',
        'hikkake' => 'Hikkake',
        'hikkakemod' => 'Hikkake Mod',
        'homingpigeon' => 'Homing Pigeon',
        'identical3crows' => 'Identical 3 Crows',
        'inneck' => 'Inneck',
        'invertedhammer' => 'Inverted Hammer',
        'kicking' => 'Kicking',
        'kickingbylength' => 'Kicking by Length',
        'ladderbottom' => 'Ladder Bottom',
        'longleggeddoji' => 'Long Legged Doji',
        'longline' => 'Long Line',
        'marubozu' => 'Marubozu',
        'matchinglow' => 'Matching Low',
        'mathold' => 'Mathold',
        'morningdojistar' => 'Morning Doji Star',
        'morningstar' => 'Morning Star',
        'onneck' => 'On Neck',
        'piercing' => 'Piercing',
        'rickshawman' => 'Rickshaw Man',
        'risefall3methods' => 'Rise Fall 3 Methods',
        'separatinglines' => 'Separating Lines',
        'shootingstar' => 'Shooting Star',
        'shortline' => 'Short Line',
        'spinningtop' => 'Spinning Top',
        'stalledpattern' => 'Stalled Pattern',
        'sticksandwich' => 'Stick Sandwich',
        'takuri' => 'Takuri',
        'tasukigap' => 'Tasuki Gap',
        'thrusting' => 'Thrusting',
        'tristar' => 'Tristar',
        'unique3river' => 'Unique 3 River',
        'upsidegap2crows' => 'Upside Gap 2 Crows',
        'xsidegap3methods' => 'Xside Gap 3 Methods',
    ]
];
